/* DO NOT EDIT THIS FILE */

#ifndef FILECHAR_H
#define FILECHAR_H

#include <stdbool.h>

#define ALPHABET_SIZE (26)
#define ALPHABET_SIZE_W_SPACE (ALPHABET_SIZE + 1)

bool countChar(char *, int[][ALPHABET_SIZE_W_SPACE]);
void printCounts(int[][ALPHABET_SIZE_W_SPACE]);

#endif /* FILECHAR_H */
